### ISSUE TITLE
Waaaay too cheap and fast to make enderpearls.

### ISSUE THREAD

**Issue by jena-s-lab** [squeek502/VeganOption#27]
Hello,

I'm sorry to come with this, that looks like a serious bug:

[Screenshots](https://imgur.com/a/yhUAN)
1. The conversion bubbles -> enderpearls doesn't require liquid ender, only water.
2. Starting with a single water source I end up with ~8 sources.

**Comment by squeek502** [comment]
I am aware of this (see #17), and it was fixed by a commit a long time ago but a new version hasn't been released. I keep putting off releasing a new version because I still have a few WIP things that I need to finish up/test, but I _really_ do need to get a new version released.

I'll try isolating the various bugfixes in a separate branch and then release a new version. Will keep this open until a new version is released with the fix included.

**Comment by squeek502** [comment]
Should be fixed in https://github.com/squeek502/VeganOption/releases/tag/v0.1.2

**Comment by jena-th** [comment]
Thanks a lot ! :) Sorry for the issue duplication.
