### ISSUE TITLE
[Harvestcraft dependent] Why no Ma Po Tofu?

### ISSUE THREAD

**Issue by Fortanono** [squeek502/VeganOption#52]
Pretty simple. This is a delicious dish made with tofu, so I feel it should be here. Pork is used in Ma Po Tofu I believe, but you could just replace it with MORE TOFU. MMM.

**Comment by squeek502** [comment]
Sorry, not going to do this for a few reasons:
- Mapo Tofu uses fermented black soybeans that I don't think would be worth adding for a single recipe
- More importantly, I don't really want to add too many foods to the mod, because one point I want the mod to get across is that veganism is not a diet, and I think having only a few food items in the mod is a good way to drive that point home.

The reason I added BBQ Tofu is because it is an inside joke from the /r/vegan and /r/vegancirclejerk communities on Reddit. See [this](https://imgur.com/a/JKPnb) for where it came from (the image titled "Cut on a bias").
