### ISSUE TITLE
Immersive Engineering integration

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#58]
Inspired by: https://twitter.com/Kane_Thornwyrd/status/689453765557006336 (see https://gist.github.com/kane-thornwyrd/a74299d563b90eefb3c7)

Not familiar with the mod (haven't actually played Minecraft in a while...), but I'm sure there's some recipes that could be added to its various machines.

**Comment by PearlCanopus** [comment]
Maybe you could implement optional recipes with IE hemp.
Seems to be a bit tighter than strings. So maybe less recipe-ception would be needed. ;)

But I have no idea at the moment, which recipes could be affected, really.

**Comment by PearlCanopus** [comment]
IE uses conveyor belts made from leather. Burlap should be usable for instead. (ok, might be more an option for IE)

Creosole oil should be usable like plant oil or cooking oil.
In other direction plant oil should be usable instead of creosole oil to ferment it to fule for the Diesel generator. Don't know whether there are "oreDict" entries possible to unify the behaviour.
