### ISSUE TITLE
Vegan option in MC 1.11.2

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [squeek502/VeganOption#80]
Maybe a stupid question, but I'm quite new to this. 
What does it need to compile it for  minecraft 1.11.2?

**Comment by squeek502** [comment]
It would need some amount of work--the changes to ItemStacks in 1.11.2 are non-trivial.

**Comment by 5t0rmr1d3r** [comment]
I'm new to the modding minecraft thingie, can you give an example? Maybe I'm able to do the work....? (i know some Java)

**Comment by elifoster** [comment]
@squeek502 I am willing to work on this with my relatively minimal free time. Should #77 get resolved first though? And should each version (1.7, 1.10, 1.11, possibly 1.12) get indefinite support?

@5t0rmr1d3r There are a few changes. Firstly ItemStacks are pretty much never null anymore. Lots of the fields have been properly encapsulated too.

**Comment by squeek502** [comment]
@elifoster When/if #77 is resolved, it would be easy to port/backport, so it doesn't need to be solved before a 1.11.2 version.

About support: it doesn't really matter to me--it might be nice to support any 1.10.2+ versions simultaneously (since the differences aren't too huge and 1.10.2 still has a playerbase afaik), but not worry about backporting stuff to 1.7.10 (mostly because the differences between 1.7.10 and 1.10.2+ would likely make it not worth the effort). But, really, I'm cool with whatever you want to do.

**Comment by elifoster** [comment]
I've begun the port at branch 1.11.2.

**Comment by 5t0rmr1d3r** [comment]
the port is on work isn't it?
because the build fails...
[veganoption_1.11.2_stacktrace.txt](https://github.com/squeek502/VeganOption/files/1131830/veganoption_1.11.2_stacktrace.txt)

**Comment by squeek502** [comment]
Yeah, still a work-in-progress.

**Comment by elifoster** [comment]
Several years later, I am skipping 1.11. In fact I'm skipping all the way to 1.20. There were forks for 1.11 and 1.12 in that time, though I'm not aware of any 1.13-1.19 forks. They are linked on the CurseForge page.
